(assert-eq '(1 2) '(1 2))
(def foo '(1 2))
(assert-eq-addr foo foo)
(assert (eq-addr? foo foo))
(assert (not (==* foo '(1 2))))
(assert-eq-addr 1 1)
(assert-eq 1 1)
(assert (not (eq-addr? 1 2)))
(assert (not (== 1 2)))
