(for (i (.. 10)) (print i " "))
(print-ln)
(for (j (.. 10 20)) (print j " "))
(print-ln)
(for (i (..= 10)) (print i " "))
(print-ln)
(for (y (..= 10 20)) (print y " "))
(print-ln)
(for (i (.. 10 20) 2) (print i " "))
(print-ln)
(for (x (..= 10 20) 2) (print x " "))
(print-ln)
